### ISSUE TITLE
Vignette?

### ISSUE THREAD

**Issue by SnowpeaSoho** [NJKlappstein/hmmSSF#1]
Hi Natasha, I have just found your paper and R package, and was hoping to read the vignette, however when I click the link on your GItHub it throws an error '404 - page not found - The main  branch of  hmmSSF  does not contain the path  vignettes/hmmSSF_introduction.pdf'. There does not seem to be a pdf associated with the downloaded package either?
Thanks for your help,
Sophie

**Comment by NJKlappstein** [comment]
Hi Sophie - thank you for flagging this! I have fixed the issue, and the PDF should now be there. Let me know if you have any questions, and I hope it's useful! 
Best,
Natasha

**Comment by SnowpeaSoho** [comment]
Thanks so much for the prompt response :)

**Comment by SnowpeaSoho** [comment]
Thank you for providing the vignette document, very helpful. Only one minor omission noted is there is a sentence or two need on p7 on the starting parameters to be passed in the fourth row of the ssf_par0 matrix ie. the selection parameters for cov1 in each state.
